# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 370)
        self.combo_list = QtWidgets.QComboBox(Dialog)
        self.combo_list.setGeometry(QtCore.QRect(70, 50, 431, 24))
        self.combo_list.setObjectName("combo_list")
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(230, 310, 90, 28))
        self.btn_ok.setObjectName("btn_ok")
        self.txt_input = QtWidgets.QLineEdit(Dialog)
        self.txt_input.setGeometry(QtCore.QRect(70, 130, 431, 28))
        self.txt_input.setObjectName("txt_input")
        self.lbl_val = QtWidgets.QLabel(Dialog)
        self.lbl_val.setGeometry(QtCore.QRect(110, 220, 371, 16))
        self.lbl_val.setObjectName("lbl_val")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_ok.setText(_translate("Dialog", "OK"))
        self.lbl_val.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
